language: node_js
dist: focal
node_js:
  - 12
  - 13

script:
  - npm run lint
  - npm test
  - sudo apt-get install wait-for-it
  - nohup npm run run-test-server &
  - wait-for-it localhost:3000
  - npm run govuk-frontend-diff

jobs:
  include:
    - stage: release to npm
      if: tag IS present
      script: npm run build
      before_deploy: cd dist
      deploy:
        on:
          tags: true
        provider: npm
        edge: true
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_AUTH_TOKEN
