language: node_js
node_js:
  - 12
  - 13

script:
  - npm run lint
  - npm test

jobs:
  include:
    - stage: deploy to gh-pages
      if: branch = main AND type = push AND fork = false
      script: npm run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: storybook-static
        on:
          branch: master

    - stage: release to npm
      if: tag IS present
      script: npm run build
      before_deploy: cd dist
      deploy:
        on:
          tags: true
        provider: npm
        edge: true
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_AUTH_TOKEN
